### PR TITLE
Add Hundred Rabbits

### PR DESCRIPTION
**Pull request by artilate**
My neovim made the file look "prettier" which is why there is a bunch of deletions and inserts.

### CODE REVIEW

**Comment by mvllow** [comment]
thanks for the addition, please format with the prettier settings in the repo 😌

**Comment by mvllow** [comment]
also, i had a look at your theme but it appears from the screenshots that those are not our colours

**Comment by artilate** [comment]
I didn't know what hundred rabbits was until I made this theme and it's quite unique. There are around 15 apps that can use the hundred rabbits theme and how they are displayed depends on the app. With the TAPE application, some colors are added that aren't apart of the theme. With another application such as left by hundred rabbits, the colors displayed will only be from the theme svg (I believe). You can see the colors by looking at the svg files.

**Comment by mvllow** [comment]
makes sense, thanks again 💜

**Pull request merged**
