### PR TITLE
feat: add tmux theme

### PR DESCRIPTION
**Pull request by mrs4ndman**
Hello!
Just created a little tmux theme with the base colorscheme. 
Will I be able to update the code for the multiple colorschemes once I get it done?
(It still has a lot to polish up)

Thanks for the opportunity

### CODE REVIEW

**Comment by mvllow** [comment]
Ciao!

I noticed in the readme you have "Temporally set to mrs4ndman until rose-pine repo integration", would you like to transfer your repository in instead of having it under community repos for the `rose-pine/tmux` namespace? If the repo is transferred, adding the "theme" topic on GitHub will automatically add it to our website and this PR will no longer be necessary.

**Pull request feedback**

Please lowercase the name tmux to match their branding.

```diff
- "name": "Tmux",
+ "name": "tmux",
```

**Theme feedback**

Please change "flavour(s)" &rarr; "variant(s)" and "base" &rarr; "main" to match our branding.

---

Thank you for making this and please let me know if you have any questions or need help 💜

**Comment by mrs4ndman** [comment]
Thanks for the feedback!

I have already made all the changes you proposed. I did realize the variable names were different from other themes on the website, so I was a bit skeptical about my own naming scheme :)

I'm all OK with the transfer, but, since I have never done anything this complex in GitHub (relatively new to VCS and repositories), I don't know exactly how to do it.

I did have a doubt, related to licensing: Is it necessary for me to put a LICENSE in the repo or is it handled in any special way? Just out of curiosity

**Comment by mvllow** [comment]
As far as the license, I'd recommend add this to the "thanks to" section to attribute Catppuccin (and anyone else):


```md
- [Catppuccin for tmux](https://github.com/catppuccin/tmux) ([license](https://github.com/catppuccin/tmux/blob/4e48b09a76829edc7b55fbb15467cf0411f07931/LICENSE))
```

Then, if you want to create a `license` file, feel free to copy one of our existing licenses, e.g. https://github.com/rose-pine/neovim/blob/main/license

I'll send you an organisation invite on GitHub so you can transfer it in. You should get an email notification and if you accept, you can go in the settings of your repository (again on GitHub) and near the bottom of the page there should be a transfer option. The repo name should be `rose-pine/tmux`. If you need any help or get stuck, I can also clone your repo, upload to our organisation, and add you as the owner :)

**Comment by mrs4ndman** [comment]
Thanks for everything!
The org joining went perfectly, and the repo is already up and running :0
License stuff is done also, will be on the Discord for more info if needed

**Comment by mvllow** [comment]
Lovely, thank you for all your work on this! Going to close this PR because the repo has been added to the website :)

**Pull request closed without merging**
